site_name: ProjectPlanner.md
site_description: Documentation for the Project Planner plugin for Obsidian
site_url: https://arctykdev.github.io/project-planner-docs
site_author: James Hawkins
repo_url: https://github.com/ArctykDev/project-planner-docs
repo_name: Project Planner Docs
edit_uri: edit/main/docs/

copyright: Copyright Â© 2026 Project Planner and its contributors.

site_dir: site # optional but recommended
strict: true # optional but recommended
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/arctyk-icon-logo.png
  favicon: assets/favicon.ico
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.instant.progress
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: custom
      primary: #7c3aed
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: #7c3aed
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Blog:
      - Blog: blog/index.md
  - Views:
      - Dashboard View: views/dashboard-view.md
      - Grid View: views/grid-view.md
      - Board View: views/board-view.md
      - Timeline View: views/timeline-view.md
      - Dependency Graph View: views/dependency-graph-view.md
      - Task Details View: views/task-details-view.md
  - Features:
      - Markdown Sync: features/markdown-sync.md
      - Task Tagging: features/daily-notes-tagging.md
      - URI Linking: features/uri-linking.md
  - Changelog: changelog.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html

plugins:
  - material/blog
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      locale: en
      enable_creation_date: false

extra:
  status:
    new: Recently added
    deprecated: Deprecated feature
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArctykDev
