site_name: Project Planner
site_description: Documentation for the Project Planner plugin for Obsidian
site_url: https://arctykdev.github.io/project-planner-docs
site_author: James Hawkins
repo_url: https://github.com/ArctykDev/project-planner-docs
repo_name: Project Planner Docs
edit_uri: edit/main/docs/

copyright: Copyright Â© 2026 Project Planner and its contributors.

site_dir: site # optional but recommended
strict: false # optional but recommended
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/projectplanner-logo.svg
  font:
    text: ui-sans-serif
  favicon: assets/favicon.ico
  custom_dir: overrides
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.instant.progress
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      primary: custom
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Blog:
      - Blog: blog/index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - First steps: getting-started/first-steps.md
  - Views:
      - Dashboard view: views/dashboard-view.md
      - Grid view: views/grid-view.md
      - Board view: views/board-view.md
      - Timeline view: views/timeline-view.md
      - Dependency Graph view: views/dependency-graph-view.md
      - Task Details view: views/task-details-view.md
  - Features:
      - Markdown sync: features/markdown-sync.md
      - Task tagging: features/daily-notes-tagging.md
      - URI linking: features/uri-linking.md
  - Community:
      - Contributing: community/contributing.md
      - Share your ideas: community/sharing-ideas.md
      - Security: community/security.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html

plugins:
  - blog:
      blog_dir: blog
      authors_file: blog/posts/.authors.yml
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      locale: en
      enable_creation_date: false

extra:
  status:
    new: Recently added
    deprecated: Deprecated feature
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArctykDev/obsidian-project-planner
