site_name: Arctyk Projects
site_description: Documentation for ArctykDev projects not part of Arctyk ITSM
site_url: https://arctykdev.github.io/arctyk-projects-docs
site_author: James Hawkins
repo_url: https://github.com/ArctykDev/arctyk-projects-docs
repo_name: Arctyk Projects Docs
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: cyan

nav:
  - Home: index.md
  - Obsidian:
      - Overview: obsidian/obsidian.md
      - Obsidian Calendar Events:
          - Obsidian Calendar Events: obsidian/obsidian-calendar-events/obsidian-calendar-events.md
          - Changelog: obsidian/obsidian-calendar-events/obsidian-calendar-events-changelog.md
      - Obsidian Project Planner:
          - Overview: obsidian/obsidian-project-planner/obsidian-project-planner.md
      - Obsidian 5 Things:
          - Overview: obsidian/obsidian-5-things/obsidian-5-things.md
  - SharePoint:
      - SharePoint: sharepoint/sharepoint.md
  - Power Platform:
      - Overview: power-platform/power-platform.md
  - WordPress:
      - WordPress: wordpress/wordpress.md
  - SNOdesk:
      - snodesk/snodesk.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - tables
  - footnotes
  - def_list
  - codehilite
  - attr_list

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      locale: en
      enable_creation_date: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArctykDev
