site_name: Arctyk Projects
site_description: Documentation for ArctykDev projects not part of Arctyk ITSM
site_url: https://arctykdev.github.io/arctyk-projects-docs
site_author: James Hawkins
repo_url: https://github.com/ArctykDev/arctyk-projects-docs
repo_name: Arctyk Projects Docs
edit_uri: edit/main/docs/

copyright: Copyright © 2025 Arctyk

site_dir: site # optional but recommended
strict: true # optional but recommended

theme:
  name: material
  logo: assets/arctyk-icon-logo.png
  favicon: assets/favicon.ico
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.instant.progress
    - navigation.tabs
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Obsidian Plugins:
      - Overview: obsidian/obsidian.md
      - Obsidian Calendar Events:
          - Overview: obsidian/obsidian-calendar-events/obsidian-calendar-events.md
          - How to Install: obsidian/obsidian-calendar-events/obsidian-calendar-events-installation.md
          - Changelog: obsidian/obsidian-calendar-events/obsidian-calendar-events-changelog.md
      - Obsidian Project Planner:
          - Overview: obsidian/obsidian-project-planner/obsidian-project-planner.md
      - Obsidian 5 Things:
          - Overview: obsidian/obsidian-5-things/obsidian-5-things.md
  - SharePoint:
      - Overview: sharepoint/sharepoint.md
  - Power Platform:
      - Overview: power-platform/power-platform.md
  - WordPress:
      - Overview: wordpress/wordpress.md
  - SNOdesk:
      - Overview: snodesk/snodesk.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html

plugins:
  - material/blog # fixed (old “blog” is not valid)
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      locale: en
      enable_creation_date: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArctykDev
