site_name: Arctyk Projects
site_description: Documentation for ArctykDev projects not part of Arctyk ITSM
site_url: https://arctykdev.github.io/arctyk-projects-docs
site_author: James Hawkins
repo_url: https://github.com/ArctykDev/arctyk-projects-docs
repo_name: Arctyk Projects Docs
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: cyan

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/overview.md
      - Integrations: projects/integrations.md
      - Obsidian:
          - Overview: projects/obsidian.md
          - Obsidian Calendar Events: projects/obsidian/obsidian-calendar-events.md
          - Obsidian Project Planner: projects/obsidian/obsidian-calendar-events.md
          - Obsidian 5 Things: projects/obsidian/obsidian-5-things.md
      - SharePoint: projects/sharepoint.md
      - WordPress: projects/wordpress.md
      - Power Platform: /projects/power-platform.md
      - Custom Apps: projects/custom-apps.md
      - Dev Tools: projects/dev-tools.md
  - About: about.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - tables
  - footnotes
  - def_list
  - codehilite
  - attr_list

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      locale: en
      enable_creation_date: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArctykDev
